In [141]:
import pandas as pd

In [142]:
meta_score = pd.read_excel("C:/Users/Emma/Desktop/metaClean43Brightspace.xlsx")

In [143]:
meta_score.head()

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,2013-06-28

In [144]:
#splits the string values into lists separated by comma
meta_score["cast"] = meta_score["cast"].str.split(",")
meta_score["awards"] = meta_score["awards"].str.split(",")

In [145]:
meta_score[["cast", "awards"]]

,cast,awards
0,NaN,NaN
1,"[John Gallagher Jr., John Goodman, Mary Elizab...","[#18MostDiscussedMovieof2016 , #1MostSharedMo..."
2,"[Jonah Hill, Morgan Freeman, Paz Vega]",NaN
3,"[Channing Tatum, Chris Pratt, Jenna Dewan]",NaN
4,NaN,NaN
...,...,...
11359,"[Ben Stiller, Kristen Wiig, Owen Wilson, PenÃ©...","[#87MostDiscussedMovieof2016 , #80MostSharedM..."
11360,"[Chevy Chase, Courteney Cox, Tim Allen]",NaN
11361,NaN,NaN
11362,NaN,"[#80BestMovieof2016 , #11MostDiscussedMovieof..."
11363,NaN,NaN

In [146]:
#creates a new data frame for actors overview
actors = pd.DataFrame(columns = ["actor_id", "actor_name"])

In [147]:
#imports data from meta score df to actors df
actors["actor_name"] = meta_score["cast"]
actors = actors.explode("actor_name")
#normalizes the data
actors["actor_name"] = actors["actor_name"].astype(str)
actors["actor_name"] = actors["actor_name"].str.lower()

In [148]:
actors.head(20)

   actor_id               actor_name
0       NaN                      NaN
1       NaN       john gallagher jr.
1       NaN             john goodman
1       NaN  mary elizabeth winstead
2       NaN               jonah hill
2       NaN           morgan freeman
2       NaN                 paz vega
3       NaN           channing tatum
3       NaN              chris pratt
3       NaN              jenna dewan
4       NaN                      NaN
5       NaN                      NaN
6       NaN                      NaN
7       NaN            camilla belle
7       NaN               marco khan
7       NaN            steven strait
8       NaN                      NaN
9       NaN                      NaN
10      NaN   hilmir snã¦r guã°nason
10      NaN           victoria abril

In [149]:
#creates actor id based on index to fill in NA cells to later 
actors["actor_id"] = actors.index + 1

In [150]:
#removes duplicates
actors.reset_index(drop=True, inplace=True)
actors["actor_name"] = actors["actor_name"].drop_duplicates()
actors.head()

   actor_id               actor_name
0         1                      NaN
1         2       john gallagher jr.
2         2             john goodman
3         2  mary elizabeth winstead
4         3               jonah hill

In [151]:
#removes NA values
actors.reset_index(drop=True, inplace=True)
actors = actors.dropna()

In [152]:
actors.head(20)

    actor_id               actor_name
1          2       john gallagher jr.
2          2             john goodman
3          2  mary elizabeth winstead
4          3               jonah hill
5          3           morgan freeman
6          3                 paz vega
7          4           channing tatum
8          4              chris pratt
9          4              jenna dewan
13         8            camilla belle
14         8               marco khan
15         8            steven strait
18        11   hilmir snã¦r guã°nason
19        11           victoria abril
20        12        gã©rard depardieu
21        12              glenn close
22        13              brad renfro
23        13          giovanni ribisi
24        13            james marsden
27        16               abby linne

In [153]:
#check for duplicates
print(actors["actor_name"].duplicated().sum())

0

In [154]:
#alphabatically sorts the names
actors = actors.sort_values(by = "actor_name")

In [155]:
actors

       actor_id                        actor_name
3025        697
10724      2388                           50 cent
578         146                           6ix9ine
7676       1666                        a martinez
47398     10352                  a. brian daniels
...         ...                               ...
38443      8528               ãorsteinn bachmann
38444      8528       ãorsteinn gunnar bjarnason
27437      6061         ãrã¶stur leã³ gunnarsson
45465      9925  ãurã­ã°ur blã¦r jã³hannsdã³ttir
47252     10308                           å½eljko

[24862 rows x 2 columns]

In [156]:
#resets the index after sorting
actors.reset_index(drop=True, inplace=True)
actors["actor_id"] = actors.index + 1

In [157]:
actors.head()

   actor_id        actor_name
0         1
1         2           50 cent
2         3           6ix9ine
3         4        a martinez
4         5  a. brian daniels

In [158]:
actors = actors.drop(index=0)

In [159]:
actors

       actor_id                        actor_name
1             2                           50 cent
2             3                           6ix9ine
3             4                        a martinez
4             5                  a. brian daniels
5             6                 a. patrice moreau
...         ...                               ...
24857     24858               ãorsteinn bachmann
24858     24859       ãorsteinn gunnar bjarnason
24859     24860         ãrã¶stur leã³ gunnarsson
24860     24861  ãurã­ã°ur blã¦r jã³hannsdã³ttir
24861     24862                           å½eljko

[24861 rows x 2 columns]

In [160]:
#actors.to_csv("C:/Users/Emma/Downloads/actors.csv", index = False)