In [48]:
import pandas as pd

In [49]:
meta_score = pd.read_excel("C:/Users/Emma/Desktop/metaClean43Brightspace.xlsx")

In [ ]:
#splits the string values into lists separated by comma
meta_score["cast"] = meta_score["cast"].str.split(",")
meta_score["awards"] = meta_score["awards"].str.split(",")

In [52]:
meta_score.head()

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,[],Lynn Hershman-Leeson,Documentary,NaN,[],70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"[John Gallagher Jr., John Goodman, Mary Elizab...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","[#18MostDiscussedMovieof2016 , #1MostSharedMo...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"[Jonah Hill, Morgan Freeman, Paz Vega]",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,[],54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"[Channing Tatum, Chris Pratt, Jenna Dewan]",Jamie Linden,"Drama,Comedy,Romance",NaN,[],61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,[],Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,[],63,7.5,2013-06-28

In [ ]:
#creates a new data frame for awards overview
awards = pd.DataFrame(columns = ["award_id", "award_name","award_body","category"])

In [ ]:
##imports data from meta score df to actors df
awards["award_name"] = meta_score["awards"]
awards = awards.explode("award_name")
#normalises the data entries
awards["award_name"] = awards["award_name"].astype(str)
awards["award_name"] = awards["award_name"].str.lower()

In [114]:
awards["award_body"] = awards["award_body"].fillna("-")
awards["category"] = awards["category"].fillna("-")
awards.head()

   award_id                    award_name award_body category
0       NaN                           NaN          -        -
1       NaN  #18mostdiscussedmovieof2016           -        -
1       NaN       #1mostsharedmovieof2016          -        -
2       NaN                           NaN          -        -
3       NaN                           NaN          -        -

In [ ]:
#creates award id based on index to fill in NA cells to later 
awards["award_id"] = awards.index + 1
awards.head()

   award_id                    award_name award_body category
0         1                           NaN          -        -
1         2  #18mostdiscussedmovieof2016           -        -
1         2       #1mostsharedmovieof2016          -        -
2         3                           NaN          -        -
3         4                           NaN          -        -

In [ ]:
#removes duplicates from the dataframe
awards.reset_index(drop=True, inplace=True)
awards["award_name"] = awards["award_name"].drop_duplicates()

In [ ]:
#removes NA values from the dataframe
awards.reset_index(drop=True, inplace=True)
awards = awards.dropna()

In [ ]:
#alphabatically sorts the names
awards = awards.sort_values(by = "award_name")

In [ ]:
#resets the index after sorting to create an id values
awards.reset_index(drop=True, inplace=True)
awards["award_id"] = awards.index + 1

In [121]:
awards.head()

   award_id                      award_name award_body category
0         1   #100mostdiscussedmovieof2001           -        -
1         2   #100mostdiscussedmovieof2002           -        -
2         3       #100mostsharedmovieof2001          -        -
3         4       #100mostsharedmovieof2002          -        -
4         5       #100mostsharedmovieof2005          -        -

In [ ]:
#awards.to_csv("C:/Users/Emma/Downloads/awards.csv",index = False)