In [38]:
#pip install sqlalchemy psycopg
import pandas as pd
from sqlalchemy import create_engine, text, inspect

In [39]:
db_url = "postgresql+psycopg://postgres:Osazuwa41@localhost:5432/movie_database"
engine = create_engine(db_url)

In [40]:
inspector = inspect(engine)
tables = inspector.get_table_names()
tables

['movie_table']

In [41]:
columns = inspector.get_columns("movie_table")
for column in columns:
    print(column["name"], column["type"])

movie_id INTEGER
movie_name TEXT
run_time DOUBLE PRECISION
rating TEXT
summary TEXT
release_date DATE
user_score DOUBLE PRECISION
meta_score DOUBLE PRECISION
url TEXT

In [27]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM movie_table"))
    print(result)

<sqlalchemy.engine.cursor.CursorResult object at 0x000001D1402E5E10>

In [42]:
movies = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\movies_table.csv")

In [45]:
movies.drop(columns = "movie_key", inplace = True)

In [49]:
movies.to_sql("movie_table",
              engine,
              if_exists="append",
              index=False)

-1

In [55]:
df = pd.read_sql("SELECT * FROM movie_table", engine)

In [57]:
movies

,movie_id,movie_name,release_date,run_time,rating,summary,user_score,meta_score,url
0,1,bakha satang,NaT,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Bakha-Satang...
1,2,antitrust,2001-01-12,109.0,PG-13,A relentless suspense thriller that enters the...,8.7,31.0,https://www.metacritic.com/movie/antitrust
2,3,santitos,2000-01-28,105.0,R,Alejandro Springall directs this Spanish-langu...,NaN,68.0,https://www.metacritic.com/movie/santitos
3,4,frank mcklusky c i,NaT,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,5,a walk to remember,2002-01-25,101.0,PG,"Set in the lowlands of North Carolina, this st...",8.3,35.0,https://www.metacritic.com/movie/a-walk-to-rem...
...,...,...,...,...,...,...,...,...,...
33971,33972,zombieland double tap,2019-10-18,99.0,R,"Columbus, Tallahasse, Wichita, and Little Rock...",6.5,55.0,https://www.metacritic.com/movie/zombieland-do...
33972,33973,zoolander,2001-09-28,89.0,R,Follows the world's most famous -- and empty-h...,7.2,61.0,https://www.metacritic.com/movie/zoolander
33973,33974,zoolander 2,2016-02-12,102.0,PG-13,Derek (Ben Stiller) and Hansel (Owen Wilson) a...,4.1,34.0,https://www.metacritic.com/movie/zoolander-2
33974,33975,zoom 2016,2016-09-02,96.0,Not Rated,A multi-dimensional interface between a comic ...,5.7,55.0,https://www.metacritic.com/movie/zoom-2016
33975,33976,zootopia,2016-03-04,108.0,PG,NaN,8.6,78.0,https://www.metacritic.com/movie/zootopia

In [56]:
df.head()

,movie_id,movie_name,run_time,rating,summary,release_date,user_score,meta_score,url
0,1,bakha satang,NaN,None,None,None,NaN,NaN,https://www.the-numbers.com/movie/Bakha-Satang...
1,2,antitrust,109.0,PG-13,A relentless suspense thriller that enters the...,2001-01-12,8.7,31.0,https://www.metacritic.com/movie/antitrust
2,3,santitos,105.0,R,Alejandro Springall directs this Spanish-langu...,2000-01-28,NaN,68.0,https://www.metacritic.com/movie/santitos
3,4,frank mcklusky c i,NaN,None,None,None,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,5,a walk to remember,101.0,PG,"Set in the lowlands of North Carolina, this st...",2002-01-25,8.3,35.0,https://www.metacritic.com/movie/a-walk-to-rem...

In [24]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33976 entries, 0 to 33975
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      33976 non-null  int64
 1   movie_name    33975 non-null  object
 2   release_date  11263 non-null  datetime64[ns]
 3   run_time      11008 non-null  float64
 4   rating        10200 non-null  object
 5   summary       5425 non-null   object
 6   user_score    9171 non-null   float64
 7   meta_score    11263 non-null  float64
 8   url           33976 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 2.3+ MB

In [47]:
from dateutil import parser
def parse_date(date):
    try:
        return parser.parse(str(date))
    except (parser.ParserError, TypeError, ValueError):
        return pd.NaT

In [48]:
movies["release_date"] = movies["release_date"].apply(parse_date)

In [32]:
df = pd.read_sql("SELECT * FROM genre_table", engine)

In [ ]:
text("SELECT * FROM genre_table")

In [33]:
df

    genre_id            genre  movie_id
0          1            Drama         1
1          2         Thriller         2
2          3           Comedy         3
3          4          Romance         4
4          5      Documentary         5
5          6            Crime         6
6          7          Fantasy         7
7          8        Biography         8
8          9          History         9
9         10          Concert        10
10        11      Performance        11
11        12              War        12
12        13           Action        13
13        14           Horror        14
14        15           Family        15
15        16        Adventure        16
16        17  Romantic Comedy        17
17        18            Sport        18
18        19         Suspense        19
19        20          Western        20
20        21          Musical        21
21        22          Mystery        22
22        23           Sci-Fi        23
23        24            Music        24
24        25        Animation        25
25        26     Black Comedy        26
26        27  Multiple Genres        27
27        28             News        28
28        29      Educational        29
29        30            Short        30
30        31          Reality        31
31        32            Adult        32
32        33        Talk-Show        33
33        34       Reality-TV        34
34        35        Film-Noir        35

In [30]:
genre = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\genre_table.csv")

In [31]:
genre.to_sql("genre_table", engine, index=False, if_exists="append")

-1

In [36]:
genre_movies = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\genre_movie_table.csv")

In [37]:
genre_movies.head()

   movie_id  gen_mov_id  genre_id
0         1           1       1.0
1         2           2       1.0
2         2           3       2.0
3         3           4       1.0
4         3           5       3.0