## Connecting the DB

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text, inspect
import glob
import os

In [2]:
db_url = "postgresql+psycopg://postgres:1234@localhost:5432/movie_database"
engine = create_engine(db_url)

In [3]:
inspector = inspect(engine)
tables = inspector.get_table_names()
tables

['award_table',
 'director_table',
 'movie_table',
 'sales_table',
 'user_reviews_table',
 'user_reviewer_table',
 'expert_reviews_table',
 'expert_reviewer_table',
 'actor_table',
 'actor_table_movie_table',
 'genre_table',
 'genre_table_movie_table',
 'studio_table',
 'studio_table_movie_table',
 'director_table_movie_table',
 'award_table_movie_table']

## Creating db tables

In [4]:
with open(r"C:\Users\ReMarkt\Documents\MDDB\database project\sql\create_tables_query.sql", "r") as file:
    create_tables = file.read()

queries = [qry.strip() for qry in create_tables.split(";") if qry.strip()]
queries[:5]

['BEGIN',
 'ALTER TABLE IF EXISTS public.sales_table DROP CONSTRAINT IF EXISTS None',
 'ALTER TABLE IF EXISTS public.user_reviews_table DROP CONSTRAINT IF EXISTS None',
 'ALTER TABLE IF EXISTS public.user_reviews_table DROP CONSTRAINT IF EXISTS None',
 'ALTER TABLE IF EXISTS public.expert_reviews_table DROP CONSTRAINT IF EXISTS None']

In [5]:
with engine.begin() as connection:
    for qry in queries:
        connection.execute(text(qry))

In [6]:
inspector = inspect(engine)
tables = inspector.get_table_names()
tables

['award_table',
 'director_table',
 'movie_table',
 'sales_table',
 'user_reviews_table',
 'user_reviewer_table',
 'expert_reviews_table',
 'expert_reviewer_table',
 'actor_table',
 'actor_table_movie_table',
 'genre_table',
 'genre_table_movie_table',
 'studio_table',
 'studio_table_movie_table',
 'director_table_movie_table',
 'award_table_movie_table']

In [7]:
columns = inspector.get_columns("genre_table_movie_table")
for column in columns:
    print(column["name"], column["type"])

gen_movie_id INTEGER
genre_id BIGINT
movie_id BIGINT

## load data into the DB

In [8]:
db_files = glob.glob(r"C:\Users\ReMarkt\Documents\MDDB\database project\data\cleaned/*csv")
db_files

['C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\actors.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\awards.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\directors.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\expert_reviewer_table.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\expert_review_table.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\genre_movie_table.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\genre_table.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\movie_actor.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\movie_award.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\movie_director.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\movie_studio.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\movie_table.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\sales_final.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\studios.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\user_reviewer_table.csv',
 'C:\\Users\\ReMarkt\\Documents\\MDDB\\database project\\data\\cleaned\\user_review_table.csv']

In [9]:
dfs = {os.path.basename(file).replace(".csv","") : pd.read_csv(file, encoding= "utf-8", encoding_errors= "ignore") for file in db_files}

In [10]:
actors = dfs["actors"].copy()
actors

       actor_id                        actor_name
0             1                           50 cent
1             2                           6ix9ine
2             3                        a martinez
3             4                  a. brian daniels
4             5                 a. patrice moreau
...         ...                               ...
24856     24857               ãorsteinn bachmann
24857     24858       ãorsteinn gunnar bjarnason
24858     24859         ãrã¶stur leã³ gunnarsson
24859     24860  ãurã­ã°ur blã¦r jã³hannsdã³ttir
24860     24861                           å½eljko

[24861 rows x 2 columns]

In [11]:
actors.to_sql("actor_table", engine, if_exists= "append", index=False)

-1

In [12]:
awards = dfs["awards"]
awards

      award_id                      award_name award_body category
0            1   #100mostdiscussedmovieof2001           -        -
1            2   #100mostdiscussedmovieof2002           -        -
2            3       #100mostsharedmovieof2001          -        -
3            4       #100mostsharedmovieof2002          -        -
4            5       #100mostsharedmovieof2005          -        -
...        ...                             ...        ...      ...
6402      6403      #9mostdiscussedmovieof2019          -        -
6403      6404      #9mostdiscussedmovieof2021          -        -
6404      6405         #9mostsharedmovieof2005          -        -
6405      6406         #9mostsharedmovieof2011          -        -
6406      6407         #9mostsharedmovieof2016          -        -

[6407 rows x 4 columns]

In [13]:
awards = awards.drop(columns= ["award_body", "category"])

In [14]:
awards.to_sql("award_table", engine, if_exists= "append", index=False)

-1

In [15]:
directors = dfs["directors"]
directors

      director_id                 director_name
0               1                  a. dean bell
1               2                   a.b. shawky
2               3                    a.j. eaton
3               4                  a.j. edwards
4               5                   aaron aites
...           ...                           ...
6131         6132  ãsa helga hjã¶rleifsdã³ttir
6132         6133            ãlã©onore faucher
6133         6134             ãmile gaudreault
6134         6135               ãtienne sauret
6135         6136                  ãva gã¡rdos

[6136 rows x 2 columns]

In [16]:
directors.to_sql("director_table", engine, if_exists="append", index=False)

-1

In [17]:
genre = dfs["genre_table"]
genre

              genre  genre_id
0             Drama         1
1          Thriller         2
2            Comedy         3
3           Romance         4
4       Documentary         5
5             Crime         6
6           Fantasy         7
7         Biography         8
8           History         9
9           Concert        10
10      Performance        11
11              War        12
12           Action        13
13           Horror        14
14           Family        15
15        Adventure        16
16  Romantic Comedy        17
17            Sport        18
18         Suspense        19
19          Western        20
20          Musical        21
21          Mystery        22
22           Sci-Fi        23
23            Music        24
24        Animation        25
25     Black Comedy        26
26  Multiple Genres        27
27             News        28
28      Educational        29
29            Short        30
30          Reality        31
31            Adult        32
32        Talk-Show        33
33       Reality-TV        34
34        Film-Noir        35

In [18]:
genre.to_sql("genre_table", engine, if_exists="append", index=False)

-1

In [19]:
movies = dfs["movie_table"]
movies

,movie_id,movie_name,release_date,run_time,rating,summary,user_score,meta_score,url
0,1,bakha satang,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Bakha-Satang...
1,2,antitrust,2001-01-12,109.0,PG-13,A relentless suspense thriller that enters the...,8.7,31.0,https://www.metacritic.com/movie/antitrust
2,3,santitos,2000-01-28,105.0,R,Alejandro Springall directs this Spanish-langu...,NaN,68.0,https://www.metacritic.com/movie/santitos
3,4,frank mcklusky c i,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,5,a walk to remember,2002-01-25,101.0,PG,"Set in the lowlands of North Carolina, this st...",8.3,35.0,https://www.metacritic.com/movie/a-walk-to-rem...
...,...,...,...,...,...,...,...,...,...
33971,33972,zombieland double tap,2019-10-18,99.0,R,"Columbus, Tallahasse, Wichita, and Little Rock...",6.5,55.0,https://www.metacritic.com/movie/zombieland-do...
33972,33973,zoolander,2001-09-28,89.0,R,Follows the world's most famous -- and empty-h...,7.2,61.0,https://www.metacritic.com/movie/zoolander
33973,33974,zoolander 2,2016-02-12,102.0,PG-13,Derek (Ben Stiller) and Hansel (Owen Wilson) a...,4.1,34.0,https://www.metacritic.com/movie/zoolander-2
33974,33975,zoom 2016,2016-09-02,96.0,Not Rated,A multi-dimensional interface between a comic ...,5.7,55.0,https://www.metacritic.com/movie/zoom-2016
33975,33976,zootopia,2016-03-04,108.0,PG,NaN,8.6,78.0,https://www.metacritic.com/movie/zootopia

In [20]:
movies["release_date"] = pd.to_datetime(movies["release_date"], errors="coerce")

In [21]:
movies.to_sql("movie_table", engine, if_exists="append", index=False)

-1

In [22]:
gen_movie = dfs["genre_movie_table"]
gen_movie

       movie_id  gen_mov_id  genre_id
0             1           1       1.0
1             2           2       1.0
2             2           3       2.0
3             3           4       1.0
4             3           5       3.0
...         ...         ...       ...
51815     33976       51816      16.0
51816     33976       51817       3.0
51817     33976       51818       6.0
51818     33976       51819      25.0
51819     33976       51820      15.0

[51820 rows x 3 columns]

In [23]:
gen_movie = gen_movie.rename(columns={"gen_mov_id" : "gen_movie_id"})
gen_movie["genre_id"] = pd.to_numeric(gen_movie["genre_id"]).astype("Int64")

In [24]:
gen_movie

       movie_id  gen_movie_id  genre_id
0             1             1         1
1             2             2         1
2             2             3         2
3             3             4         1
4             3             5         3
...         ...           ...       ...
51815     33976         51816        16
51816     33976         51817         3
51817     33976         51818         6
51818     33976         51819        25
51819     33976         51820        15

[51820 rows x 3 columns]

In [25]:
gen_movie.to_sql('genre_table_movie_table', engine, if_exists="append", index=False)

-1

In [26]:
studio = dfs["studios"]
studio

      studio_id                      studio_name
0             1  "dia" productions gmbh & co. kg
1             2              "g" productions llc
2             3                  01 distribution
3             4                        108 media
4             5                       1091 media
...         ...                              ...
1113       1114                          youtube
1114       1115                  zealot pictures
1115       1116                  zeitgeist films
1116       1117                           zenpix
1117       1118                   zipporah films

[1118 rows x 2 columns]

In [27]:
studio.to_sql("studio_table", engine, if_exists="append", index=False)

-1

In [28]:
movie_actor = dfs["movie_actor"]
movie_actor

       actor_id  movie_id  movie_actor_id
0         20731         2               1
1         23177         2               2
2         17601         3               3
3         21517         5               4
4         15394         5               5
...         ...       ...             ...
51367      2638     33974           51368
51368     19009     33974           51369
51369     24235     33974           51370
51370     17601     33975           51371
51371     17601     33976           51372

[51372 rows x 3 columns]

In [29]:
movie_actor.to_sql('actor_table_movie_table', engine, if_exists="append", index=False)

-1

In [30]:
movie_award = dfs["movie_award"]
movie_award

      award_id  movie_id  movie_award_id
0         4729         2               1
1         2829         5               2
2           19         5               3
3         5592        16               4
4         2998        21               5
...        ...       ...             ...
6340      1682     33974            6341
6341      5741     33974            6342
6342      5373     33976            6343
6343        39     33976            6344
6344       426     33976            6345

[6345 rows x 3 columns]

In [31]:
movie_award.to_sql('award_table_movie_table', engine, if_exists="append", index=False)

-1

In [32]:
movie_director = dfs["movie_director"]
movie_director

       director_id  movie_id  movie_director_id
0             4743         2                  1
1              167         3                  2
2               74         5                  3
3              380        10                  4
4              924        11                  5
...            ...       ...                ...
11244         5183     33972              11245
11245          662     33973              11246
11246          662     33974              11247
11247         4703     33975              11248
11248          918     33976              11249

[11249 rows x 3 columns]

In [33]:
movie_director.to_sql('director_table_movie_table', engine, if_exists="append", index=False)

-1

In [34]:
movie_studio = dfs["movie_studio"]
movie_studio

       studio_id  movie_id  movie_studio_id
0            655         2                1
1            722         3                2
2           1081         5                3
3            511        10                4
4            755        11                5
...          ...       ...              ...
10909        257     33972            10910
10910        782     33973            10911
10911        782     33974            10912
10912        888     33975            10913
10913       1077     33976            10914

[10914 rows x 3 columns]

In [35]:
movie_studio.to_sql('studio_table_movie_table', engine, if_exists="append", index=False)

-1

In [36]:
user_reviewer = dfs["user_reviewer_table"]
user_reviewer

           reviewer_name  reviewer_id
0           longbottom94            1
1                martinb            2
2                 jaakko            3
3                  capor            4
4               orwellb.            5
...                  ...          ...
104553      thehollowone       319652
104554           mariajc       319653
104555       commongamer       319656
104556    juiliopaublito       319659
104557   porridgeboy3000       319660

[104558 rows x 2 columns]

In [37]:
user_reviewer.to_sql('user_reviewer_table', engine, if_exists="append", index=False)

-1

In [38]:
expert_reviewer = dfs["expert_reviewer_table"]
expert_reviewer["reviewer_name"] = expert_reviewer["reviewer_name"].str.replace('"', "")
expert_reviewer

             reviewer_name  reviewer_id
0            andrew ohehir            1
1               a.o. scott            2
2                     none            3
3              noel murray            4
4          joshua rothkopf            5
...                    ...          ...
1180   russell scott smith       217804
1181        debra birnbaum       219231
1182         kevin allison       219371
1183          leah mclaren       220469
1184             joe mader       224583

[1185 rows x 2 columns]

In [39]:
expert_reviewer.to_sql('expert_reviewer_table', engine, if_exists="append", index=False)

-1

In [40]:
expert_review = dfs["expert_review_table"]
expert_review = expert_review.rename(columns={"indv_score" : "score"})
expert_review["date_posted"] = pd.to_datetime(expert_review["date_posted"], errors="coerce")
expert_review

,url,score,date_posted,review,tone,movie_id,review_id,reviewer_id
0,https://www.metacritic.com/movie/bronson,100.0,NaT,bronson owes a little or a lot to kubrick s c...,25.77,19568,1,1.0
1,https://www.metacritic.com/movie/bronson,90.0,NaT,bronson invites you to admire its protagonist...,99.00,19568,2,2.0
2,https://www.metacritic.com/movie/bronson,90.0,NaT,whether it s peterson/bronson s more theatric...,2.89,19568,3,3.0
3,https://www.metacritic.com/movie/bronson,83.0,NaT,there are two bronsons on display here: the i...,25.77,19568,4,4.0
4,https://www.metacritic.com/movie/bronson,80.0,NaT,refn has somehow found his way to an authenti...,25.77,19568,5,5.0
...,...,...,...,...,...,...,...,...
238968,https://www.metacritic.com/movie/spirited-away,80.0,NaT,this movie -- which is equally appealing to c...,25.77,32752,238969,114.0
238969,https://www.metacritic.com/movie/spirited-away,75.0,NaT,"too intense for the youngest viewers, but tee...",2.30,32752,238970,168.0
238970,https://www.metacritic.com/movie/spirited-away,75.0,NaT,delivers chunks of yellow submarine and the p...,25.77,32752,238971,115.0
238971,https://www.metacritic.com/movie/spirited-away,75.0,NaT,has the power to transport us to a different ...,93.61,32752,238972,164.0
238972,https://www.metacritic.com/movie/spirited-away,75.0,NaT,"a lovely, evocative tour de force. so why doe...",99.00,32752,238973,1715.0

In [42]:
expert_review.to_sql('expert_reviews_table', engine, if_exists="append", index=False)

-1

In [43]:
user_review = dfs["user_review_table"]
user_review["date_posted"] = pd.to_datetime(user_review["date_posted"], errors="coerce")
user_review

,url,indv_score,date_posted,review,likes,dislikes,tone,movie_id,review_id,reviewer_id
0,https://www.metacritic.com/movie/bronson,8.0,2013-04-25,many have dismissed this film for not explori...,2.0,2.0,13.73,19568,1,1.0
1,https://www.metacritic.com/movie/bronson,9.0,2009-10-13,anyone who doesn t like this movie simply jus...,0.0,1.0,62.59,19568,2,2.0
2,https://www.metacritic.com/movie/bronson,10.0,2012-07-19,not sure what to think at this film at first....,1.0,1.0,86.40,19568,3,3.0
3,https://www.metacritic.com/movie/bronson,6.0,2009-10-13,nicely portrayed but it lacks the elements to...,0.0,1.0,99.00,19568,4,4.0
4,https://www.metacritic.com/movie/bronson,8.0,2009-10-10,bronson is more than entertainment. it is art...,0.0,0.0,96.76,19568,5,5.0
...,...,...,...,...,...,...,...,...,...,...
319657,https://www.metacritic.com/movie/spirited-away,10.0,2021-09-06,a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a+a...,0.0,0.0,25.77,32752,319658,712.0
319658,https://www.metacritic.com/movie/spirited-away,10.0,2021-11-25,in my opinion spirited away is one of the bes...,0.0,0.0,94.75,32752,319659,319659.0
319659,https://www.metacritic.com/movie/spirited-away,10.0,2021-12-31,usually i don t like watching movies that muc...,0.0,0.0,98.56,32752,319660,319660.0
319660,https://www.metacritic.com/movie/spirited-away,10.0,2022-01-20,studio ghibli s gripping masterpiece spirited...,0.0,0.0,99.00,32752,319661,169.0
319661,https://www.metacritic.com/movie/spirited-away,10.0,2022-02-07,words cannot describe how amazing this movie ...,0.0,0.0,99.00,32752,319662,22314.0

In [45]:
user_review.to_sql('user_reviews_table', engine, if_exists="append", index=False)

-1

In [46]:
with engine.begin() as connection:
    df = pd.read_sql("SELECT * FROM actor_table", connection)

display(df)

       actor_id                        actor_name
0             1                           50 cent
1             2                           6ix9ine
2             3                        a martinez
3             4                  a. brian daniels
4             5                 a. patrice moreau
...         ...                               ...
24856     24857               ãorsteinn bachmann
24857     24858       ãorsteinn gunnar bjarnason
24858     24859         ãrã¶stur leã³ gunnarsson
24859     24860  ãurã­ã°ur blã¦r jã³hannsdã³ttir
24860     24861                           å½eljko

[24861 rows x 2 columns]