In [1]:
#Importing libries requiered for cleaning the data
import pandas as pd
import re
from dateutil import parser

In [2]:
#Loading the data into a pandas dataframe
df1 = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\Data Files\sales.csv")
df2 = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\Data Files\metaClean43Brightspace.csv")
df3 = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\Data Files\UserReviewsClean43LIWC.csv", low_memory=False)
df4 = pd.read_csv(r"C:\Users\hp\Documents\DBMS Project\Data Files\ExpertReviewsClean43LIWC.csv")

In [3]:
#previewing the dataframes
display(df1.head())
display(df2.head())
display(df3.head())
display(df4.head())

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,NaN,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,NaN,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,2013-06-28

,url,idvscore,reviewer,dateP,Rev,thumbsUp,thumbsTot,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,8,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,2,2,113,94.05,32.91,...,4.42,0.0,0.0,0.0,0.0,0.88,0,1.77,0.00,0.0
1,https://www.metacritic.com/movie/bronson,9,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,0,1,103,57.11,38.53,...,0.97,0.0,0.0,0.0,0.0,0.00,0,1.94,5.83,0.0
2,https://www.metacritic.com/movie/bronson,10,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,1,1,143,75.73,66.27,...,0.70,0.0,0.0,0.0,0.0,0.00,0,1.40,0.00,1.4
3,https://www.metacritic.com/movie/bronson,6,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,0,1,14,83.81,23.75,...,0.00,0.0,0.0,0.0,0.0,0.00,0,14.29,0.00,0.0
4,https://www.metacritic.com/movie/bronson,8,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,0,0,20,93.26,69.14,...,0.00,0.0,0.0,0.0,0.0,0.00,0,10.00,0.00,0.0

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,11.52,6.70,25.77,...,4.00,0.00,0.0,0.0,0.0,0.00,0,8.00,0.0,0.0
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,97.69,1.00,99.00,...,6.67,0.00,0.0,0.0,0.0,0.00,0,6.67,0.0,0.0
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,77.33,7.84,2.89,...,7.50,0.00,0.0,0.0,0.0,12.50,0,5.00,0.0,2.5
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,99.00,1.00,25.77,...,5.13,2.56,0.0,0.0,0.0,0.00,0,5.13,0.0,0.0
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,89.42,1.79,25.77,...,8.33,0.00,0.0,0.0,0.0,4.17,0,8.33,0.0,0.0

In [4]:
#Extracting the url from all dataframes
sales_url = df1["url"]
meta_url = df2["url"]
user_url = df3["url"]
expert_url = df4["url"]

In [5]:
#Concatenating all urls and converting them into a dataframe
urls = pd.concat([sales_url, meta_url, user_url, expert_url], ignore_index=True)
urls_df = pd.DataFrame(urls, columns=["url"])
urls_df.tail()

                                                   url
600606  https://www.metacritic.com/movie/spirited-away
600607  https://www.metacritic.com/movie/spirited-away
600608  https://www.metacritic.com/movie/spirited-away
600609  https://www.metacritic.com/movie/spirited-away
600610  https://www.metacritic.com/movie/spirited-away

In [6]:
#Extracting the movie names from the urls and storing them in a new column
urls_df["movie_name"] =urls_df["url"].str.split('/', expand=True).iloc[:, -1].str.replace('-', ' ')
urls_df.head()

                                                 url              movie_name
0  https://www.the-numbers.com/movie/Bakha-Satang...  Bakha Satang (S Korea)
1        https://www.the-numbers.com/movie/Antitrust               Antitrust
2         https://www.the-numbers.com/movie/Santitos                Santitos
3  https://www.the-numbers.com/movie/Frank-McKlus...      Frank McKlusky C I
4  https://www.the-numbers.com/movie/Walk-to-Reme...      Walk to Remember A

In [7]:
#Creating a function to clean the movie names and remove duplicates
def remove_duplicates(movie_names):
    """converts the movie names to lowercase, removes any text in parentheses or brackets, 
    removes punctuation, and sorts the words in the movie name. 
    It then checks if the sorted movie name is already in a set of seen movie names. If it is not, 
    it adds the sorted movie name to the set and appends the original cleaned movie name to a list of unique movie names. 
    Finally, it returns the list of unique movie names in"""
    seen = {}
    unique_movie_names = []
    stop_words = {"the", "a", "an", "of", "and", "in", "to", "for"}
    for index, movie_name in movie_names.items():
        movie_name = str(movie_name).lower()
        cleaned = re.sub(r"\s*[\(\[].*[a-zA-Z].*[\)\]]", "", movie_name)
        cleaned = re.sub(r"[^\w\s]", "", cleaned)
        sort_movie_name = tuple(sorted([word for word in cleaned.split() if word not in stop_words]))
        if sort_movie_name not in seen:
            seen[sort_movie_name] = len(unique_movie_names)
            unique_movie_names.append((index, cleaned))
        else:
            position = seen[sort_movie_name]
            unique_movie_names[position] = (index, cleaned)
    return unique_movie_names

In [9]:
def remove_duplicates(movie_names):
    seen = {}
    unique_movie_names = []
    stop_words = {"the", "a", "an", "of", "and", "in", "to", "for"}

    for index, movie_name in movie_names.items():
        movie_name = str(movie_name).lower()
        cleaned = re.sub(r'\s*[\(\[].*[a-zA-Z].*[\)\]]', '', movie_name)
        cleaned = re.sub(r'[^\w\s]', '', cleaned)

        sort_movie_name = tuple(
            sorted(word for word in cleaned.split() if word not in stop_words)
        )

        if sort_movie_name not in seen:
            seen[sort_movie_name] = len(unique_movie_names)
            unique_movie_names.append((index, cleaned))
        else:
            # Replace the first occurrence with the second
            position = seen[sort_movie_name]
            unique_movie_names[position] = (index, cleaned)
        

    return unique_movie_names

In [8]:
#Cleaning the movie names and removing duplicates
cleaned_movie_names = remove_duplicates(urls_df["movie_name"])
cleaned_movie_names

[(0, 'bakha satang'),
 (563075, 'antitrust'),
 (552267, 'santitos'),
 (3, 'frank mcklusky c i'),
 (590124, 'a walk to remember'),
 (5, 'zig zag'),
 (6, 'takhte siah'),
 (7, 'angry monk reflections on tibet the'),
 (8, '30 years to life'),
 (383292, 'the killing of john lennon'),
 (384259, 'mad money'),
 (11, 'little chenier'),
 (382459, 'over her dead body'),
 (13, 'ano em que meus pais sairam de ferias o'),
 (14, '120'),
 (382383, 'the other boleyn girl'),
 (16, 'lawyer walks into a bar a'),
 (17, 'rondine la'),
 (18, 'jodaeiye nader az simin'),
 (19, 'pariah 2011'),
 (393179, 'war horse'),
 (21, 'habemus papam'),
 (22, 'ivan tsarevich i seryy volk'),
 (23, 'sicario room 164 el'),
 (364961, 'extremely loud and incredibly close'),
 (363871, 'angels crest'),
 (26, 'paranormal xperience 3d'),
 (474900, 'darkest hour'),
 (367837, 'miss minoes'),
 (378139, 'we bought a zoo'),
 (30, 'minuscule la vallee des fourmis perdues'),
 (31, 'kiseki'),
 (369335, 'in the land of blood and honey'),
 (33, 'prince of the himalayas'),
 (34, 'don 2'),
 (393567, 'we are the giant'),
 (36, 'wang pai'),
 (37, 'young kieslowski the 2015'),
 (448796, 'last cab to darwin'),
 (39, 'cong cong na nian'),
 (40, 'ghadi'),
 (41, 'fair play'),
 (478396, 'meru'),
 (43, 'station to station'),
 (44, 'karachi se lahore'),
 (45, 'atrapa la bandera'),
 (46, 'alma'),
 (47, 'boca juniors 3d la pelicula'),
 (48, 'life of josutty'),
 (478487, 'welcome to leith'),
 (50, 'eso que llaman amor'),
 (51, 'man who saved the world the'),
 (52, 'yuan ling ren ou'),
 (53, 'hip hop eration'),
 (54, 'kleine ziege sturer bock'),
 (55, 'vesvese cin tuzagi'),
 (432939, 'truth 2015'),
 (57, 'geunomida'),
 (58, 'wo shi zheng ren'),
 (59, 'sarancha'),
 (60, 'hamoni'),
 (61, 'dobbiamo parlare'),
 (62, '600 millas'),
 (63, 'hot sugars cold world'),
 (64, 'hell and back'),
 (65, 'rajini murugan'),
 (66, 'histoire de fou une'),
 (430866, 'break point'),
 (68, 'desu noto light up the new world'),
 (29327, 'disturbing the peace'),
 (70, 'star wars ep vii the force awakens'),
 (71, 'doctor who the power of the daleks'),
 (72, 'grand jeu le'),
 (73, 'bellas de noche'),
 (440786, 'the revenant 2015'),
 (75, 'unmarried wife the'),
 (76, 'sha mo zhi xin'),
 (77, 'poveri ma ricchi'),
 (78, 'nuo lietuvos nepabegsi'),
 (79, 'somewhere connected'),
 (80, 'peor de los deseos lo'),
 (81, 'pere fils therapie'),
 (82, 'di qiu zui hou de ye wang'),
 (83, 'doktor martin zahada v beskydech'),
 (84, 'battle of tortoise and rabbit'),
 (85, 'alibaba the three golden hair'),
 (86, 'duan pian er'),
 (87, 'yun nan chong gu yunnan valley'),
 (88, 'two small pigs brave the mysterious island'),
 (89, 'trolled 2018'),
 (90, 'tiempo despues'),
 (91, 'stan and ollie 2018'),
 (92, 'work wife the 2018'),
 (93, 'tarp musu mergaiciu'),
 (94, 'trilece'),
 (95, 'rio mekong'),
 (96, 'simmba'),
 (97, 'pech to nie grzech'),
 (98, 'musaadenizle buyukler'),
 (99, 'most beautiful season the'),
 (100, 'shou ji kuang xiang'),
 (101, 'one shot'),
 (102, 'konna yofuke ni banana kayo kanashiki jitsuwa'),
 (103, 'njan prakashan'),
 (104, 'minha vida em marte'),
 (105, 'k g f chapter 1'),
 (106, 'kleine drache kokosnuss auf in den dschungel der'),
 (107, 'jeombaki hanbandoeui gongryong 2 saeroun nakwon'),
 (393130, 'chef'),
 (372661, 'benji'),
 (110, 't34'),
 (111, 'boru'),
 (112, 'junge muss an die frische luft der'),
 (113, 'yolki posledniye'),
 (114, 'cuando brillan las estrellas'),
 (115, 'au bout des doigts'),
 (116, 'violent desir de bonheur un'),
 (117, 'befana vien di notte la'),
 (118, 'pmc deo beong keo'),
 (119, 'moschettieri del re la penultima missione'),
 (120, 'mult v kino vypusk no 87'),
 (121, 'homme fidele l'),
 (580, 'perfectos desconocidos'),
 (123, 'zerk'),
 (124, 'destroyer 2018'),
 (125, 'zero'),
 (126, 'yanimda kal'),
 (127, 'ye wen hui chuan zhang tianzhi'),
 (128, 'mia et le lion blanc'),
 (129, 'wu lin guai shou'),
 (130, 'kamen raida heisei jenereshonzu foeba'),
 (131, 'welcome to marwen 2018'),
 (132, 'vergara'),
 (374605, 'vice 2018'),
 (134, 'tian qi yu bao'),
 (135, 'soul of shui people in 1944 the'),
 (136, 'snezhnaya koroleva zazerkale'),
 (137, 'unknown distance'),
 (138, 'silukkuvarpatti singam'),
 (139, 'revenge of phantom knight the'),
 (140, 'padi padi leche manasu'),
 (141, 'sukut evi'),
 (142, 'porno para principiantes'),
 (143, 'patrolman baoyin'),
 (578403, 'last resort'),
 (145, 'national theatre live antony and cleopatra'),
 (146, 'maari 2'),
 (147, 'kanaa'),
 (148, 'hugo paco luis y tres chicas de rosa'),
 (149, 'kurtlar ve cakallar'),
 (150, 'fabeltjeskrant de grote dierenbos spelen'),
 (433421, 'the connection'),
 (152, 'delaware shore 2018'),
 (153, 'dantza'),
 (154, 'd p a detetives do predio azul 2 o filme'),
 (5747, 'between worlds'),
 (156, 'antariksham 9000 kmph'),
 (157, 'blue amber'),
 (158, 'ailo une odyssee en laponie'),
 (159, 'adanga maru'),
 (160, 'tri bogatyrya i naslednitsa prestola'),
 (161, 'bolshoi ballet the nutcracker 2018'),
 (162, 'holmes and watson 2018'),
 (163, 'zanjas'),
 (164, 'its march 3rd again'),
 (165, 'wedding party 2 the destination dubai'),
 (166, 'sin filtro'),
 (167, 'yao ling ling'),
 (168, 'politseyskiy s rublyovki novogodniy bespredel'),
 (169, 'parayi bulduk'),
 (170, 'napoli velata'),
 (171, 'klases susitikimas berniukai sugrizta'),
 (172, 'kalavaadiya pozhuthugal'),
 (173, 'momo'),
 (174, 'gulu mermaid 2'),
 (175, 'gandarrappido the revenger squad'),
 (176, 'fala serio mae'),
 (177, 'echange des princesses l'),
 (178, 'okka kshanam'),
 (179, 'forget about nick'),
 (180, 'come un gatto in tangenziale'),
 (181, 'seuwingkizeu'),
 (182, 'capri revolution'),
 (183, 'maya'),
 (184, 'mayakwang'),
 (185, 'nachtwacht de poort der zielen'),
 (186, 'empereur de paris l'),
 (187, 'gendre de ma vie le'),
 (188, 'amici come prima'),
 (189, 'zhong guo he huo ren 2'),
 (190, 'mary poppins returns 2018'),
 (191, 'christmas carol a 2018'),
 (192, 'wedding the'),
 (193, 'yo kai watch movie 5 forever friends'),
 (194, 'volver a boedo'),
 (195, 'yuli'),
 (196, 'turtle odyssey'),
 (197, 'three words to forever'),
 (198, 'trote'),
 (199, 'that way madness lies'),
 (200, 'vida que te agenciaste la'),
 (201, 'there will be ample time'),
 (202, 'stolen fariytales'),
 (203, 'cat kapi ask'),
 (204, 'skjelvet'),
 (205, 'caffe'),
 (206, 'seethakaathi'),
 (456449, 'balloon'),
 (208, 'barkley'),
 (370103, 'basmati blues'),
 (210, 'asya'),
 (211, 'anons'),
 (212, 'aruvi'),
 (213, 'dvizhenie vverkh'),
 (214, 'er dai yao jing'),
 (215, '1987 when the day comes'),
 (216, 'qian ren 3 yan zhi da zuo zhan'),
 (217, 'revenge girl'),
 (477851, 'phantom thread'),
 (219, 'berliner philharmoniker new year s eve concert 2017'),
 (220, 'yao mao zhuan'),
 (465931, 'all the money in the world'),
 (222, 'tri bogatyrya i printsessa egipta'),
 (223, 'tout la haut'),
 (224, 'tiger zinda hai'),
 (225, 'velaikkaran'),
 (226, 'second time around the'),
 (227, 'paris opera ballet tribute to jerome robbins'),
 (228, 'painted skin the double mask'),
 (229, 'mochila de plomo'),
 (230, 'yolki novye'),
 (373655, 'the mule 2018'),
 (232, 'odiyan'),
 (233, 'miamor perdido'),
 (234, 'met opera la traviata 2018'),
 (235, 'ming wang xing shi ke'),
 (236, 'man who stole banksy the'),
 (237, 'keepers of the flame'),
 (238, 'journal 64'),
 (239, 'jesucristo superstar un hito en la historia del musical espanol'),
 (240, 'johnny'),
 (241, 'holding hands'),
 (242, 'haru matsu bokura'),
 (243, 'impulso'),
 (244, 'eoleuni doimyeon'),
 (245, 'if beale street could talk 2018'),
 (246, 'den pobedy'),
 (247, 'dragon ball super broly'),
 (503021, 'the first time'),
 (249, 'conversazioni atomiche'),
 (250, 'da xiang xi di er zuo'),
 (251, 'spindl'),
 (252, 'sakka podu podu raja'),
 (253, 'romans'),
 (254, 'chun tian de ma la song'),
 (255, 'rangreza'),
 (256, 'seven fright nights 2017'),
 (257, 'promesse de l aube la'),
 (258, 'muumien joulu'),
 (476736, 'the post'),
 (260, 'quizas hoy'),
 (261, 'mult v kino vypusk no 65'),
 (262, 'miseinen dakedo kodomo janai'),
 (473454, 'mollys game'),
 (264, 'lesa humanitat'),
 (265, 'martilarin efendisi'),
 (266, 'hotel infierno'),
 (267, 'huisvrouwen bestaan niet'),
 (268, 'jing hun qi you'),
 (269, 'hostiles 2017'),
 (270, 'hello'),
 (271, 'gordon and paddy'),
 (272, 'garde alternee'),
 (273, 'dus kirginlari'),
 (274, 'cbeebies christmas show thumbelina the'),
 (466665, 'father figures'),
 (276, 'bon bini holland 2'),
 (277, 'beyond white space 2018'),
 (278, 'bana bir soygun yaz 2'),
 (279, 'bhajjo veero ve'),
 (280, 'hangman 2017'),
 (281, 'antidote 2018'),
 (282, 'andre rieu s sydney town hall concert an australian celebration'),
 (283, 'singsu'),
 (284, 'maine 2018'),
 (285, 'why are we creative the centipedes dilemma'),
 (286, 'il testimone invisibile'),
 (287, 'ask bu mu'),
 (288, 'khrustal'),
 (289, 'owarani hito miyazaki hayao'),
 (380649, 'bumblebee'),
 (291, 'bird box 2018'),
 (292, 'beau voyou un'),
 (293, 'photographer the'),
 (294, 'spider man into the spider verse 3d 2018'),
 (295, 'roma 2018'),
 (296, 'gaelic curse the'),
 (297, 'pachamama'),
 (298, 'remi sans famille'),
 (299, 'deadman standing 2018'),
 (300, 'dawning'),
 (301, 'dr huang danian'),
 (471490, 'downsizing'),
 (303, 'doctor who twice upon a time'),
 (304, 'cuando los hijos regresan'),
 (305, 'belalilar'),
 (306, 'arth the destination'),
 (307, 'before i die 2017'),
 (308, 'aci tatli eksi'),
 (309, 'aadu 2'),
 (310, 'lucky man the 2017'),
 (467705, 'pitch perfect 3'),
 (312, 'masterpiece'),
 (313, 'mca middle class abbayi'),
 (314, 'ji qi zhi xue'),
 (315, 'xin li zui zhi cheng shi zhi guang'),
 (316, 'namiya'),
 (466252, 'jumanji welcome to the jungle'),
 (318, 'zoco de la buri buri el'),
 (319, 'yokai watch 4'),
 (320, 'dieses bescheuerte herz'),
 (321, 'versprechen das'),
 (322, 'unexpectedly yours'),
 (323, 'super vacanze di natale'),
 (324, 'holiday inn the new irving berlin musical'),
 (325, 'buttons'),
 (326, 'yuan qu de mu ge'),
 (327, 'subrahmanyapuram'),
 (328, 'son cikis'),
 (329, 'snowman and the snowdog the'),
 (330, 'vox lux 2018'),
 (331, 'mult v kino vypusk no 86'),
 (332, 'second act 2018'),
 (333, 'rey el'),
 (334, 'seytan gecidi enhara'),
 (335, 'pupille'),
 (336, 'racetime'),
 (337, 'por amor al arte'),
 (406250, 'a christmas carol'),
 (339, 'parque mayer'),
 (340, 'paranin kokusu'),
 (341, 'norm of the north keys to the kingdom 2018'),
 (342, 'party s just beginning the 2018'),
 (343, 'ruleta rusa'),
 (344, 'mountain rest'),
 (345, 'sundowners'),
 (346, 'mi pequeno gran hombre'),
 (347, 'poyraz karayel kuresel sermaye'),
 (348, 'permanent 2017'),
 (349, 'papita 2da base'),
 (350, 'poveri ma ricchissimi'),
 (351, 'pescadores'),
 (352, 'old beast'),
 (353, 'nina perro'),
 (354, 'novogodniy perepolokh'),
 (355, 'natale da chef'),
 (356, 'monsoon shootout'),
 (357, 'midnight man the 2017'),
 (358, 'muchos hijos un mono y un castillo'),
 (359, 'masoch el camino del perro'),
 (434146, 'maria by callas'),
 (361, 'journey of bhangover'),
 (362, 'hard kaur'),
 (363, 'nona 2018'),
 (364, 'k3 love cruise'),
 (365, 'game of ayodhya'),
 (366, 'droles de petites betes'),
 (367, 'papatya'),
 (368, 'ek andekha sach'),
 (369, 'merry men the real yoruba demons'),
 (370, 'love live sunshine aqours 4th lovelive sailing to the sunshine'),
 (374399, 'mary queen of scots'),
 (372, 'ma mere est folle'),
 (373, 'left hand and right hand'),
 (374, 'love afterlife'),
 (375, 'la scala attila'),
 (376, 'la ultima busqueda'),
 (377, 'kafalar karisik'),
 (378, 'kuru'),
 (379, 'kedarnath'),
 (380, 'hospitality 2018'),
 (381, 'frank and ava 2018'),
 (382, 'jin ji de nan hai'),
 (383, 'gekijoban haikara san ga toru zenpen tokyo dai roman'),
 (384, 'eso que nos enamora'),
 (385, 'eia joulud tondikakul'),
 (386, 'elephants 2018'),
 (387, 'dulce sabor del limon el'),
 (388, 'dumplin 2018'),
 (389, 'devushka s kosoy'),
 (390, 'drugs'),
 (391, 'deuxieme etoile la'),
 (392, 'desheredados los'),
 (14923, 'desolation'),
 (394, 'blizkie'),
 (471551, 'the ballad of lefty brown'),
 (396, 'chainbreakers the'),
 (397, '8 nengoshi no hanayome'),
 (398, 'instant dreams'),
 (399, 'algo fayo'),
 (400, 'rilu rilu fairilu the movie'),
 (401, 'ai de pa si ka'),
 (402, 'bright 2017'),
 (403, 'murder in mansfield a'),
 (404, 'dolgaya doroga domoy'),
 (405, 'star wars ep viii the last jedi'),
 (406, 'along with the gods the two worlds'),
 (434110, 'divide and conquer the story of roger ailes'),
 (408, 'confins du monde les'),
 (409, 'apache warrior'),
 (410, 'coming back out ball movie the'),
 (411, 'gangcheolbi'),
 (412, 'chaco'),
 (469360, 'the greatest showman'),
 (414, 'central park 2018'),
 (415, 'boya la'),
 (416, 'certi brko'),
 (417, 'bernie the dolphin'),
 (418, 'ben is back 2018'),
 (419, 'bizim icin sampiyon'),
 (420, 'banjara the truck driver'),
 (421, 'back roads 2018'),
 (422, 'asterix le secret de la potion magique'),
 (423, 'asher 2018'),
 (424, 'belly of the whale the'),
 (425, 'apuntes para una pelicula de atracos'),
 (426, 'zapovednik'),
 (427, 'uchu sentai kyuurenja tai supesu sukuwaddo'),
 (428, 'twiceland'),
 (429, 'tabaluga'),
 (430, 'prima pietra la'),
 (431, 'sem par nechistikh'),
 (432, 'santiago italia'),
 (433, 'tueurs'),
 (434, 'stebuklas'),
 (435, 'stars 80 la suite'),
 (436, 'sentidos los'),
 (437, 'qi man dun jia'),
 (438, 'richie'),
 (492663, 'love is all you need'),
 (474428, 'the rape of recy taylor'),
 (441, 'pueblo hecho cancion un'),
 (470210, 'the pirates of somalia'),
 (443, 'santa and cie'),
 (444, 'oteki taraf'),
 (445, 'zhgi'),
 (446, 'november criminals'),
 (447, 'on adim'),
 (448, 'national theatre live young marx'),
 (449, 'maide nin altin gunu'),
 (388031, 'makala'),
 (451, 'lerd'),
 (452, 'royal opera house the nutcracker 2017 18'),
 (453, 'north of peking the'),
 (466592, 'just getting started'),
 (455, 'jia ru wang zi shui zhao le'),
 (456, 'libenjyeo'),
 (457, 'llueven vacas'),
 (458, 'first kiss'),
 (459,
  'kamen raida heisei jenereshonzu fainaru birudo ando eguzeido wizu rejendo raida'),
 (3925, 'hope road'),
 (461, 'claras ghost 2018'),
 (28687, 'ama'),
 (463, 'beongaemaenui bimil'),
 (464, '100 dinge'),
 (465, 'aquaman 2018'),
 (466, 'jinsei furutsu'),
 (467, 'tyrel 2018'),
 (468, 'mortal engines 2018'),
 (469, 'running man'),
 (470, 'life is a belief'),
 (471, 'water lilies of monet the magic of water and light'),
 (472, 'dog 13'),
 (473, 'waiting for me in heaven'),
 (474, 'until judge do us apart'),
 (13588, 'vision'),
 (476, 'tus desperdicios y otros manjares'),
 (477, 'slay belles 2018'),
 (478, 'i am evidence'),
 (475698, 'i tonya'),
 (480, 'hollow in the land'),
 (481, 'gogitas new life'),
 (482, 'tiger 2018'),
 (483, 'doeorak'),
 (484, 'un giorno all improvviso'),
 (485, 'gek van geluk'),
 (486, 'gardiennes les'),
 (487, 'from the ground up'),
 (488, 'galpon de mascaras'),
 (489, 'forbidden'),
 (490, 'fukrey returns'),
 (491, 'fe de etarras'),
 (492, 'duvka za baloncheta'),
 (466208, 'ferdinand'),
 (494, 'fan zha feng bao'),
 (495, 'destiny kamakura monogatari'),
 (496, 'cometa el su perro y su mundo'),
 (497, 'fang hua'),
 (489783, 'bullet to the head'),
 (499, 'cemento el documental'),
 (500, 'askeladden i dovregubbens hall'),
 (501, 'sermon on the mount'),
 (502, 'cho haeng'),
 (503, 'surviving christmas with the relatives'),
 (504, 'smart christmas'),
 (505, 'sky stream'),
 (25263, 'royal opera house the nutcracker'),
 (507, 'sauver ou perir'),
 (508, 'quinqui stars'),
 (509, 'song of back and neck 2018'),
 (510, 'and the winner isnt'),
 (511, 'route 33'),
 (512, 'plagi breslau'),
 (513, 'people s republic of desire'),
 (913, 'please remember me'),
 (515, 'mulai'),
 (516, 'miriam miente'),
 (517, 'louis theroux love without limits'),
 (518, 'legend of tang dynasty 2'),
 (519, 'lola et ses freres'),
 (520, 'ovunque proteggimi'),
 (521, 'kido senshi gandamu nt'),
 (522, 'hotel explotacion las kellys'),
 (523, 'hedefim sensin'),
 (524, 'julia y el zorro'),
 (525, 'isabelle'),
 (526, 'head full of honey 2018'),
 (527, 'fantastic dream trip'),
 (528, 'ghostbox cowboy 2018'),
 (529, 'premio il'),
 (530, 'pororo dinosaur island adventure'),
 (531, 'insulte l'),
 (532, 'dolaonda 2017'),
 (533, 'wonder wheel 2017'),
 (534, 'wo yao xing fu'),
 (535, 'woman of no importance a 2017'),
 (536, 'viraam'),
 (537, 'vele hemels boven de zevende'),
 (538, 'verao danado'),
 (539, 'villa la'),
 (469309, 'the tribes of palos verdes'),
 (3435, 'ugly duckling the'),
 (542, 'umbral'),
 (543, 'tera intezaar'),
 (544, 'touken ranbu hanamaru makuai kaisouroku'),
 (545, 'tantei wa bar ni iru 3'),
 (546, 'thiruttu payale 2'),
 (547, 'soldier grandpa'),
 (548, 'solar'),
 (549, 'thrill ride 2016'),
 (550, 'exterminadores do alem contra a loira do banheiro'),
 (551, 'fake partner'),
 (552, 'sinfonia en abril'),
 (553, 'er shi sui'),
 (554, 'durante la tormenta'),
 (438013, 'diamantino'),
 (556, 'driverx 2018'),
 (557, 'chvilky'),
 (558, 'borc'),
 (559, 'entre dos aguas'),
 (560, 'bolshoi ballet don quixote'),
 (561, 'bi bei shang geng bei shang de gu shi'),
 (562, 'blood brother 2018'),
 (563, 'bathtubs over broadway 2018'),
 (564, 'araghe sard'),
 (565, 'behold my heart'),
 (566, '2 0'),
 (567, 'vse ili nichego'),
 (568, 'uomo che compro la luna l'),
 (569, 'spitak'),
 (570, 'seven deadly sins prisoners of the sky the'),
 (429131, 'ride'),
 (572, 'se son rose'),
 (573, 'saem'),
 (574, 'que leon'),
 (575, 'provodnik'),
 (576, 'si tu voyais son coeur'),
 (577, 'shadowman'),
 (578, 'prani k mani'),
 (579, 'psychopaths 2017'),
 (581, 'posoki'),
 (477924, 'the shape of water'),
 (583, 'plonger'),
 (584, 'o fim da inocencia'),
 (585, 'opera de paris don carlos'),
 (472551, 'the new radical'),
 (587, 'ninato'),
 (588, 'mujeres en foco film festival 2017'),
 (589, 'maximum impact 2017'),
 (590, 'metallica quebec magnetic'),
 (591, 'love beats rhymes'),
 (375086, 'love cecil'),
 (484095, 'life and nothing more'),
 (594, 'kvarteto'),
 (595, 'kolovrat'),
 (596, 'korfez'),
 (597, 'mao pai jian hu ren'),
 (473123, 'kill me please'),
 (599, 'meow wolf origin story'),
 (600, 'kiwi christmas'),
 (601, 'mowgli legend of the jungle 2018'),
 (414892, 'respect'),
 (603, 'os parcas'),
 (604, 'gukgabudoui nal'),
 (832, 'smile from the mountain a'),
 (606, 'hello life'),
 (607, 'possession of hannah grace the 2018'),
 (608, 'piripkura'),
 (609, 'super kids attack'),
 (610, 'zhong guo lan kui'),
 (611, 'mult v kino vypusk no 85'),
 (612, 'doubles vies'),
 (613, 'write when you get work 2018'),
 (614, 'vendran lluvias suaves'),
 (615, 'unidad xv'),
 (423505, 'yomeddine'),
 (617, 'thimiru pudichavan'),
 (618, '8 remains'),
 (619, 'todas las mujeres que conozco'),
 (620, 'unga astrid'),
 (621, 'jupiter holdja'),
 (622, 'inoperable 2017'),
 (623, 'keplers dream'),
 (624, 'judge zhongkui'),
 (542379, 'the grudge'),
 (626, 'hagane no renkinjutsushi'),
 (627, 'gecmisteki sir'),
 (628, 'gangster land'),
 (629, 'firangi'),
 (630, 'est tout pour moi c'),
 (631, 'eighth day of a week the'),
 (632, 'eat locals'),
 (633, 'drawing home'),
 (634, 'camino a marte'),
 (475538, 'the disaster artist'),
 (636, 'daisy winters 2017'),
 (637, 'breaking brooklyn'),
 (638, 'dian di lian meng'),
 (639, 'bolshoi ballet the nutcracker'),
 (640, 'souvenir the movie mariya takeuchi theater live'),
 (641, 'superlopez'),
 (642, 'seguimi'),
 (643, 'save my dogs'),
 (644, 'sirdys'),
 (645, 'strange colours'),
 (646, 'royal edinburgh military tattoo the'),
 (647, 'rang panjab'),
 (648, 'put seylere'),
 (649, 'on the basis of sex 2018'),
 (650, 'qi pao xian sheng'),
 (651, 'na stojaka v kine'),
 (652, 'mimi a liza zahada vianocneho svetla'),
 (653, 'pattinapakkam'),
 (654, 'milosc jest wszystkim'),
 (655, 'nativity rocks'),
 (656, 'maniac tales'),
 (657, 'marriage palace'),
 (658, 'mauvaises herbes'),
 (659, 'misterio del padre pio el'),
 (660, 'badsville'),
 (661, 'big time'),
 (662, 'aska geldik'),
 (663, 'another wolfcop'),
 (664, 'annadurai'),
 (665, 'al desierto'),
 (666, 'aile arasinda'),
 (667, 'alien invasion s u m 1'),

In [9]:
#Assigning the indexes and titles to urls_df
indexes, titles = zip(*cleaned_movie_names)
urls_df = urls_df.loc[list(indexes)].copy()
urls_df["movie_name"] = titles
display(urls_df.shape)
display(urls_df.head())

(33976, 2)

                                                      url          movie_name
0       https://www.the-numbers.com/movie/Bakha-Satang...        bakha satang
563075         https://www.metacritic.com/movie/antitrust           antitrust
552267          https://www.metacritic.com/movie/santitos            santitos
3       https://www.the-numbers.com/movie/Frank-McKlus...  frank mcklusky c i
590124  https://www.metacritic.com/movie/a-walk-to-rem...  a walk to remember

In [10]:
#Merging the cleaned movie names with the meta dataframe
movies = df2.merge(urls_df, on="url", how="right")
movies.head()

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate,movie_name
0,https://www.the-numbers.com/movie/Bakha-Satang...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bakha satang
1,https://www.metacritic.com/movie/antitrust,Antitrust,MGM Distribution,| PG-13,109.0,"Ryan Phillippe,Tim Robbins",Peter Howitt,"Drama,Thriller",A relentless suspense thriller that enters the...,#68MostDiscussedMovieof2001,31.0,8.7,2001-01-12,antitrust
2,https://www.metacritic.com/movie/santitos,Santitos,New Yorker Films,| R,105.0,NaN,Alejandro Springall,"Drama,Comedy",Alejandro Springall directs this Spanish-langu...,NaN,68.0,NaN,2000-01-28,santitos
3,https://www.the-numbers.com/movie/Frank-McKlus...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,frank mcklusky c i
4,https://www.metacritic.com/movie/a-walk-to-rem...,A Walk to Remember,Warner Bros. Pictures,| PG,101.0,"Mandy Moore,Shane West",Adam Shankman,"Drama,Romance","Set in the lowlands of North Carolina, this st...","#28MostDiscussedMovieof2002 , #10MostSharedMov...",35.0,8.3,2002-01-25,a walk to remember

In [14]:
#Checking the data types and the missing values in the merged dataframe
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33976 entries, 0 to 33975
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   url         33976 non-null  object
 1   title       11263 non-null  object
 2   studio      10914 non-null  object
 3   rating      10200 non-null  object
 4   runtime     11008 non-null  float64
 5   cast        7583 non-null   object
 6   director    11249 non-null  object
 7   genre       11243 non-null  object
 8   summary     5425 non-null   object
 9   awards      4351 non-null   object
 10  metascore   11263 non-null  float64
 11  userscore   9171 non-null   float64
 12  RelDate     11263 non-null  datetime64[ns]
 13  movie_name  33976 non-null  object
dtypes: datetime64[ns](1), float64(3), object(10)
memory usage: 3.6+ MB

In [12]:
#Creating a function to convert date to datetime
def parse_date(date):
    """Converts messy dates to datetime and turns pure strings or non date vales to NaT"""
    try:
        return parser.parse(str(date))
    except (parser.ParserError, TypeError, ValueError):
        return pd.NaT

In [13]:
#Converting the "RelDate" column to datetime format, coercing errors to NaT for invalid dates
movies["RelDate"] = movies["RelDate"].apply(parse_date)

In [15]:
#Assigning a unique movie_id to each movie based on the index of the dataframe and creating my movies table with the required columns
movies["movie_id"] = movies.index + 1
movies_table = movies[["movie_id","movie_name", "RelDate", "runtime", "rating", "summary", "userscore", "metascore", "url"]].copy()

In [16]:
movies_table.head()

,movie_id,movie_name,RelDate,runtime,rating,summary,userscore,metascore,url
0,1,bakha satang,NaT,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Bakha-Satang...
1,2,antitrust,2001-01-12,109.0,| PG-13,A relentless suspense thriller that enters the...,8.7,31.0,https://www.metacritic.com/movie/antitrust
2,3,santitos,2000-01-28,105.0,| R,Alejandro Springall directs this Spanish-langu...,NaN,68.0,https://www.metacritic.com/movie/santitos
3,4,frank mcklusky c i,NaT,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,5,a walk to remember,2002-01-25,101.0,| PG,"Set in the lowlands of North Carolina, this st...",8.3,35.0,https://www.metacritic.com/movie/a-walk-to-rem...

In [17]:
#Renaming the columns in the movies_table dataframe to match the desired format
movies_table.rename(columns={"RelDate": "release_date", "runtime": "run_time",
                             "userscore": "user_score", "metascore": "meta_score"}, inplace=True)

In [18]:
#Removing the or symbol
movies_table["rating"] = movies_table["rating"].str.replace("|", "")

In [19]:
#Confirming the data types
movies_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33976 entries, 0 to 33975
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      33976 non-null  int64
 1   movie_name    33976 non-null  object
 2   release_date  11263 non-null  datetime64[ns]
 3   run_time      11008 non-null  float64
 4   rating        10200 non-null  object
 5   summary       5425 non-null   object
 6   user_score    9171 non-null   float64
 7   meta_score    11263 non-null  float64
 8   url           33976 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 2.3+ MB

In [20]:
#Save as csv
movies_table.to_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\movie_table.csv", index=False)

In [21]:
#Extracting the Genres
sales_genre = df1[["url", "genre"]].copy()
meta_genre = df2[["url", "genre"]].copy()
genre_df = pd.concat([sales_genre, meta_genre], ignore_index=True)

In [22]:
genre_df.head()

                                                 url              genre
0  https://www.the-numbers.com/movie/Bakha-Satang...              Drama
1        https://www.the-numbers.com/movie/Antitrust  Thriller/Suspense
2         https://www.the-numbers.com/movie/Santitos                NaN
3  https://www.the-numbers.com/movie/Frank-McKlus...                NaN
4  https://www.the-numbers.com/movie/Walk-to-Reme...              Drama

In [23]:
#Standardizing the Genres
genre_df["genre"] = genre_df["genre"].str.replace(r"/", ", ", regex=True)
genre_df.head(2)

                                                 url               genre
0  https://www.the-numbers.com/movie/Bakha-Satang...               Drama
1        https://www.the-numbers.com/movie/Antitrust  Thriller, Suspense

In [24]:
#Merging the Genre table with the cleaned movie table
genre_df_m = genre_df.merge(movies_table, on= "url", how= "right")
genre_df_m.head()

,url,genre,movie_id,movie_name,release_date,run_time,rating,summary,user_score,meta_score
0,https://www.the-numbers.com/movie/Bakha-Satang...,Drama,1,bakha satang,NaT,NaN,NaN,NaN,NaN,NaN
1,https://www.metacritic.com/movie/antitrust,"Drama,Thriller",2,antitrust,2001-01-12,109.0,PG-13,A relentless suspense thriller that enters the...,8.7,31.0
2,https://www.metacritic.com/movie/santitos,"Drama,Comedy",3,santitos,2000-01-28,105.0,R,Alejandro Springall directs this Spanish-langu...,NaN,68.0
3,https://www.the-numbers.com/movie/Frank-McKlus...,NaN,4,frank mcklusky c i,NaT,NaN,NaN,NaN,NaN,NaN
4,https://www.metacritic.com/movie/a-walk-to-rem...,"Drama,Romance",5,a walk to remember,2002-01-25,101.0,PG,"Set in the lowlands of North Carolina, this st...",8.3,35.0

In [25]:
#Extracting the Genre and movies
genre_m_list = genre_df_m[["genre", "movie_id"]].copy()

In [26]:
#Splitting and exploding the Genre to map it with the movie ID
genre_m_list["genre"] = genre_m_list["genre"].str.split(",")
g_list = genre_m_list.explode(column= "genre", ignore_index= True)

In [27]:
#Attaching an id to the relationship
g_list["gen_mov_id"] = g_list.index +1
g_list

           genre  movie_id  gen_mov_id
0          Drama         1           1
1          Drama         2           2
2       Thriller         2           3
3          Drama         3           4
4         Comedy         3           5
...          ...       ...         ...
51815  Adventure     33976       51816
51816     Comedy     33976       51817
51817      Crime     33976       51818
51818  Animation     33976       51819
51819     Family     33976       51820

[51820 rows x 3 columns]

In [ ]:
#Save the relationship to csv
#g_list.to_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\genre_movie_table.csv", index=False)

In [28]:
#Extracting the unique Genre from the relationship
unique_genre = g_list.drop_duplicates(subset="genre").dropna().reset_index().drop(columns=["gen_mov_id", "movie_id", "index"])
unique_genre["genre_id"] = unique_genre.index +1
unique_genre

              genre  genre_id
0             Drama         1
1          Thriller         2
2            Comedy         3
3           Romance         4
4       Documentary         5
5             Crime         6
6           Fantasy         7
7         Biography         8
8           History         9
9           Concert        10
10      Performance        11
11              War        12
12           Action        13
13           Horror        14
14           Family        15
15        Adventure        16
16  Romantic Comedy        17
17            Sport        18
18         Suspense        19
19          Western        20
20          Musical        21
21          Mystery        22
22           Sci-Fi        23
23            Music        24
24        Animation        25
25     Black Comedy        26
26  Multiple Genres        27
27             News        28
28      Educational        29
29            Short        30
30          Reality        31
31            Adult        32
32        Talk-Show        33
33       Reality-TV        34
34        Film-Noir        35

In [ ]:
#Saving the unique genre to csv
#unique_genre.to_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\genre_table.csv", index=False)

In [29]:
genre_movie_list = g_list.merge(unique_genre, on= "genre", how= "left")

In [30]:
genre_movie_list = genre_movie_list.drop(columns = "genre")

In [32]:
genre_movie_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51820 entries, 0 to 51819
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   movie_id    51820 non-null  int64
 1   gen_mov_id  51820 non-null  int64
 2   genre_id    50494 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 1.2 MB

In [87]:
genre_movie_list["genre_id"] = genre_movie_list["genre_id"].astype("Int64")

In [84]:
genre_movie_list.to_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\genre_movie_table.csv", index=False)

In [33]:
df3.head()

,url,idvscore,reviewer,dateP,Rev,thumbsUp,thumbsTot,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,8,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,2,2,113,94.05,32.91,...,4.42,0.0,0.0,0.0,0.0,0.88,0,1.77,0.00,0.0
1,https://www.metacritic.com/movie/bronson,9,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,0,1,103,57.11,38.53,...,0.97,0.0,0.0,0.0,0.0,0.00,0,1.94,5.83,0.0
2,https://www.metacritic.com/movie/bronson,10,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,1,1,143,75.73,66.27,...,0.70,0.0,0.0,0.0,0.0,0.00,0,1.40,0.00,1.4
3,https://www.metacritic.com/movie/bronson,6,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,0,1,14,83.81,23.75,...,0.00,0.0,0.0,0.0,0.0,0.00,0,14.29,0.00,0.0
4,https://www.metacritic.com/movie/bronson,8,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,0,0,20,93.26,69.14,...,0.00,0.0,0.0,0.0,0.0,0.00,0,10.00,0.00,0.0

In [34]:
#Checking the unique url in the reviews
df3["url"].str.split("/", expand=True).iloc[:,2].unique()

array(['www.metacritic.com'], dtype=object)

In [35]:
df3.shape

(319662, 100)

In [36]:
#Extracting the required columns
user_review = df3[["url", "idvscore", "reviewer", "dateP", "Rev", "thumbsUp", "thumbsTot", "Tone"]].copy()

In [37]:
user_review["title"] = user_review["url"].str.split("/", expand=True).iloc[:,-1]

In [38]:
stop_words = {"the", "a", "an", "of", "and", "in", "to", "for"}
def normalized_movie_key(name, stopwords):
    name = name.lower()
    name = re.sub(r'\s*[\(\[].*[a-zA-Z].*[\)\]]', "", name)
    name = name.replace("+", "")
    name = re.sub(r"[^\w\s]", " ", name)
    words = sorted([word for word in name.split() if word not in stop_words])
    return " ".join(words)

In [39]:
user_review["movie_key"] = user_review["title"].apply(lambda x: normalized_movie_key(x, stopwords=stop_words))
movies_table["movie_key"] = movies_table["movie_name"].apply(lambda x: normalized_movie_key(x, stopwords=stop_words))

In [40]:
user_review_m = user_review.merge(movies_table[["movie_key", "movie_id"]], on= "movie_key", how= "left")

In [41]:
user_review_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319662 entries, 0 to 319661
Data columns (total 11 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   url        319662 non-null  object
 1   idvscore   316258 non-null  object
 2   reviewer   316255 non-null  object
 3   dateP      316249 non-null  object
 4   Rev        316249 non-null  object
 5   thumbsUp   316082 non-null  object
 6   thumbsTot  316086 non-null  object
 7   Tone       319662 non-null  float64
 8   title      319662 non-null  object
 9   movie_key  319662 non-null  object
 10  movie_id   319662 non-null  int64
dtypes: float64(1), int64(1), object(9)
memory usage: 26.8+ MB

In [42]:
user_review_m = user_review_m.drop(columns= ["movie_key", "title"]).rename(columns= {"idvscore" : "indv_score",
                                                                                    "dateP" : "date_posted",
                                                                                    "Rev" : "review",
                                                                                    "thumbsUp" : "likes",
                                                                                    "thumbsTot" : "dislikes",
                                                                                    "Tone" : "tone"})

In [43]:
user_review_m["reviewer"] = user_review_m["reviewer"].str.replace("'", "").str.lower()
user_review_m["date_posted"] = user_review_m["date_posted"].str.replace("'", "").str.strip()
user_review_m["review"] = user_review_m["review"].str.replace("'", "").str.lower()

In [48]:
user_review_m["date_posted"] = user_review_m["date_posted"].apply(parse_date)
user_review_m["likes"] = pd.to_numeric(user_review_m["likes"], errors= "coerce").astype("Int64")
user_review_m["dislikes"] = pd.to_numeric(user_review_m["dislikes"], errors = "coerce").astype("Int64")
user_review_m["indv_score"] = pd.to_numeric(user_review_m["indv_score"], errors="coerce")

In [49]:
user_review_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319662 entries, 0 to 319661
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   url          319662 non-null  object
 1   indv_score   316253 non-null  float64
 2   reviewer     316255 non-null  object
 3   date_posted  316249 non-null  datetime64[ns]
 4   review       316249 non-null  object
 5   likes        316081 non-null  Int64
 6   dislikes     316080 non-null  Int64
 7   tone         319662 non-null  float64
 8   movie_id     319662 non-null  int64
dtypes: Int64(2), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 22.6+ MB

In [52]:
user_review_m.head()

,url,indv_score,reviewer,date_posted,review,likes,dislikes,tone,movie_id
0,https://www.metacritic.com/movie/bronson,8.0,longbottom94,2013-04-25,many have dismissed this film for not explori...,2,2,13.73,19568
1,https://www.metacritic.com/movie/bronson,9.0,martinb,2009-10-13,anyone who doesn t like this movie simply jus...,0,1,62.59,19568
2,https://www.metacritic.com/movie/bronson,10.0,jaakko,2012-07-19,not sure what to think at this film at first....,1,1,86.40,19568
3,https://www.metacritic.com/movie/bronson,6.0,capor,2009-10-13,nicely portrayed but it lacks the elements to...,0,1,99.00,19568
4,https://www.metacritic.com/movie/bronson,8.0,orwellb.,2009-10-10,bronson is more than entertainment. it is art...,0,0,96.76,19568

In [53]:
user_review_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319662 entries, 0 to 319661
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   url          319662 non-null  object
 1   indv_score   316253 non-null  float64
 2   reviewer     316255 non-null  object
 3   date_posted  316249 non-null  datetime64[ns]
 4   review       316249 non-null  object
 5   likes        316081 non-null  Int64
 6   dislikes     316080 non-null  Int64
 7   tone         319662 non-null  float64
 8   movie_id     319662 non-null  int64
dtypes: Int64(2), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 22.6+ MB

In [55]:
user_review_m["review_id"] = user_review_m.index +1

In [56]:
df4.head()

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,11.52,6.70,25.77,...,4.00,0.00,0.0,0.0,0.0,0.00,0,8.00,0.0,0.0
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,97.69,1.00,99.00,...,6.67,0.00,0.0,0.0,0.0,0.00,0,6.67,0.0,0.0
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,77.33,7.84,2.89,...,7.50,0.00,0.0,0.0,0.0,12.50,0,5.00,0.0,2.5
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,99.00,1.00,25.77,...,5.13,2.56,0.0,0.0,0.0,0.00,0,5.13,0.0,0.0
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,89.42,1.79,25.77,...,8.33,0.00,0.0,0.0,0.0,4.17,0,8.33,0.0,0.0

In [58]:
df4["url"].str.split("/", expand=True).iloc[:,2].unique()

array(['www.metacritic.com'], dtype=object)

In [59]:
#Extracting the required columns
expert_review = df4[["url", "idvscore", "reviewer", "dateP", "Rev", "Tone"]].copy()

In [60]:
expert_review["title"] = expert_review["url"].str.split("/", expand=True).iloc[:,-1]
expert_review["movie_key"] = expert_review["title"].apply(lambda x: normalized_movie_key(x, stopwords=stop_words))

In [61]:
expert_review_m = expert_review.merge(movies_table[["movie_key", "movie_id"]], on= "movie_key", how= "left")

In [62]:
expert_review_m = expert_review_m.drop(columns= ["movie_key", "title"]).rename(columns= {"idvscore" : "indv_score",
                                                                                    "dateP" : "date_posted",
                                                                                    "Rev" : "review",
                                                                                    "Tone" : "tone"})

In [63]:
expert_review_m["reviewer"] = expert_review_m["reviewer"].str.replace("'", "").str.lower()
expert_review_m["date_posted"] = expert_review_m["date_posted"].str.replace("'", "").str.strip()
expert_review_m["review"] = expert_review_m["review"].str.replace("'", "").str.lower()

In [64]:
expert_review_m["date_posted"] = expert_review_m["date_posted"].apply(parse_date)

In [65]:
expert_review_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238973 entries, 0 to 238972
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   url          238973 non-null  object
 1   indv_score   238971 non-null  float64
 2   reviewer     238971 non-null  object
 3   date_posted  134489 non-null  datetime64[ns]
 4   review       238971 non-null  object
 5   tone         238973 non-null  float64
 6   movie_id     238973 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 12.8+ MB

In [66]:
expert_review_m["review_id"] = expert_review_m.index +1

In [67]:
user_review_m.to_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\user_review_table.csv", index=False)

In [70]:
expert_review_m.to_csv(r"C:\Users\hp\Documents\DBMS Project\clean_tables\expert_review_table.csv", index=False)