In [147]:
import pandas as pd

In [148]:
meta_score = pd.read_excel("C:/Users/Emma/Desktop/metaClean43Brightspace.xlsx")
movie_table = pd.read_csv("C:/Users/Emma/Downloads/movies_table.csv")
award_table = pd.read_csv("C:/Users/Emma/Downloads/awards.csv")

In [149]:
#splits the string values into lists separated by comma
meta_score["cast"] = meta_score["cast"].str.split(",")
meta_score["awards"] = meta_score["awards"].str.split(",")

In [150]:
#creates new dataframe for the relationship table
movie_award = pd.DataFrame(columns = ["url", "award_name"])

In [151]:
movie_award["url"] = meta_score["url"]
movie_award["award_name"] = meta_score["awards"]

In [152]:
#expands the created lists into rows
movie_award = movie_award.explode("award_name")
#normalises the data entries
movie_award["award_name"] = movie_award["award_name"].astype(str)
movie_award["award_name"] = movie_award["award_name"].str.lower()

In [153]:
movie_award.head()

,url,award_name
0,https://www.metacritic.com/movie/!women-art-re...,NaN
1,https://www.metacritic.com/movie/10-cloverfiel...,#18mostdiscussedmovieof2016
1,https://www.metacritic.com/movie/10-cloverfiel...,#1mostsharedmovieof2016
2,https://www.metacritic.com/movie/10-items-or-less,NaN
3,https://www.metacritic.com/movie/10-years,NaN

In [154]:
#merges the combined table movie_award with actor table based on the award name
movie_award = movie_award.merge(award_table, on="award_name")

In [155]:
movie_award = movie_award.drop("award_name", axis=1)

In [156]:
movie_award.head()

,url,award_id,award_body,category
0,https://www.metacritic.com/movie/10-cloverfiel...,2415,-,-
1,https://www.metacritic.com/movie/10-cloverfiel...,296,-,-
2,https://www.metacritic.com/movie/10000-bc,2638,-,-
3,https://www.metacritic.com/movie/10000-bc,493,-,-
4,https://www.metacritic.com/movie/102-dalmatians,5006,-,-

In [157]:
#merges the combined table movie_award with movie table based on the url
movie_award = movie_award.merge(movie_table, on="url")

In [158]:
#removes the unnecessary columns
movie_award = movie_award.drop(columns=['url','movie_name', 'RelDate', 'runtime', 'rating','summary', 'userscore', 'metascore'])

In [159]:
#sorts the movie_actor table asc based on movie id
movie_award = movie_award.sort_values(by = "movie_id")

In [160]:
movie_award

      award_id award_body category  movie_id
436       4729          -        -         2
223       2829          -        -         5
224         19          -        -         5
5362      5592          -        -        16
6096      2998          -        -        21
...        ...        ...      ...       ...
6341      1682          -        -     33974
6340      5741          -        -     33974
6342      5373          -        -     33976
6343        39          -        -     33976
6344       426          -        -     33976

[6345 rows x 4 columns]

In [161]:
#removes unnecessary columns
movie_award = movie_award.drop(columns=['award_body','category'])

In [162]:
#resets the index and creates a new id for movie-actor combination
movie_award.reset_index(drop=True, inplace=True)
movie_award["movie_award_id"] = movie_award.index + 1

In [163]:
movie_award.head()

   award_id  movie_id  movie_award_id
0      4729         2               1
1      2829         5               2
2        19         5               3
3      5592        16               4
4      2998        21               5

In [164]:
#movie_award.to_csv("C:/Users/Emma/Downloads/movie_award.csv",index = False)